# temporary data storage - to dzialalo tylko jak nie mialem entity, zobacz potem dlaczego...
#spring.jpa.defer-datasource-initialization=false
#spring.datasource.url = 'jdbc:h2:file:/data/sample'
#spring.datasource.url = 'jdbc:h2:file:C:/data/sample'